/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import java.util.Arrays
import java.util.regex.Pattern

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    println(start())
    println(listOf("a", "b", "c"))
    println(useFoo())
    println("containsEven(listOf(1, 3, 5)) ${containsEven(listOf(1, 3, 5))}")
    println("containsEven(listOf(1, 2, 5)) ${containsEven(listOf(1, 2, 5))}")
    println("""Pattern.matches(getPattern(), "13 JUN 1992") ${Pattern.matches(getPattern(), "13 JUN 1992")}""")
    println(getPeople())

    //Nullable types
    sendMessageToClient(Client(PersonalInfo("mail@example")), "hello world", SimpleMailer())
    sendMessageToClient(Client(PersonalInfo(null)), "hello world", SimpleMailer())
    sendMessageToClient(Client(null), "hello world", SimpleMailer())
    sendMessageToClient(null, "hello world", SimpleMailer())
    sendMessageToClient(Client(PersonalInfo("mail@example")), null, SimpleMailer())

    println("isMale(UserInfo(1)) ${isMale(UserInfo(1))}")
    println("isMale(UserInfo(2)) ${isMale(UserInfo(2))}")
    println("isMale(null) ${isMale(null)}")

    //Smart cast
    println(eval(Num(1)))
    println(eval(Sum(Num(1), Num(2))))
    try {
        println(eval(Minus(Num(1), Num(2))))
    } catch(e: Exception) {
        e.printStackTrace()
    }

    //Extension functions
    println(1.r())
    println(Pair(1, 2).r())

    println(sortList(listOf(1, 3, 2)))
    println(sortList(listOf(3, 1, 2)))
    println(sortListSAM(listOf(3, 1, 2)))
    println(sortListExtensionsCollections(listOf(1, 3, 2)))
}
